const errorHandler = async (req, res, next, err) => {
  try {
  } catch (err) {}
};

module.exports = errorHandler;
